# Site settings
title: Visual Data Analysis Lab
author:
  name: Jan Aerts
  email: jan.aerts@kuleuven.be
description: > # this means to ignore newlines until "baseurl:"
  From data to insight – Putting the human back in the loop of data analysis
baseurl: "/~jaerts" # the subpath of your site, e.g. /blog/
url: "http://vda-lab.be" # the base hostname & protocol for your site
twitter_username: jandot
permalink: /:year/:month/:title

gems:
  - jekyll-feed

# Build settings
markdown: kramdown
