# Site settings
title: Visual Data Analysis Lab
author:
  name: Jan Aerts
  email: jan.aerts@kuleuven.be
description: > # this means to ignore newlines until "baseurl:"
  From data to insight – Putting the human back in the loop of data analysis
url: "http://vda-lab.github.io" # the base hostname & protocol for your site
twitter_username: jandot
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
